php-checks/src/main/java/org/sonar/php/checks/FormattingStandardCheck.java, php-checks/src/test/resources/checks/formattingCheck/FunctionSpacingCheck.php
Fix for https://jira.sonarsource.com/browse/SONARPHP-619
Since php allows for case insensitive internal function calls "Echo" or even "EcHo" should be recognized as internal functions. Converting the callee string to lowercase accomplishes this, because PHPKeyword is defined in lower case.
=> SOANRPHP-619 FunctionSpacingCheck: exception on non-lowercase "internal functional function" call without parenthesis

php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java, php-frontend/src/test/java/org/sonar/php/parser/expression/MemberExpressionTest.java, php-frontend/src/test/java/org/sonar/php/parser/expression/PrimaryExpressionTest.java, php-frontend/src/test/java/org/sonar/php/parser/statement/StatementTest.java
This reverts commit 55b7bad0f7867dd1049a74b828751c73da6b1770.
=> Revert "SONARPHP-735 Parse array initializer as primary expression (#253)"

php-checks/src/main/java/org/sonar/php/checks/UseOfEmptyReturnValueCheck.java, php-checks/src/test/resources/checks/UseOfEmptyReturnValueCheck.php
IMHO there is al false positive for rule S3699 when using the `new` keyword to instantiate a new object, e.g.:
`$header = new Header($preseller);`
I added a test and also a fix for this issue. Please review. Please let me know if I also need to create a ticket or something.
Thanks a lot.
=> SONARPHP-766 Fix FP for UseOfEmptyReturnValueCheck on "new" operator

php-frontend/src/main/java/org/sonar/php/parser/LexicalConstant.java
After this change, github.com/Dolibarr/dolibarr/htdocs/includes/phpoffice/phpexcel/Classes/PHPExcel/Calculation/Statistical.php can be parsed in less than one second instead of several minutes.
=> SONARPHP-953 [Performance] Several minutes is spent in LexicalConstant.NUMERIC_LITERAL regular expression when parsing a file

.cirrus.yml, .cirrus/regular_mvn_build_deploy_analyze, .cirrus/set_maven_build_version, its/plugin/plugins/php-custom-rules-plugin/pom.xml, its/plugin/plugins/pom.xml, its/plugin/pom.xml, its/plugin/tests/pom.xml, its/pom.xml, its/ruling/pom.xml, php-checks/pom.xml, php-frontend/pom.xml, pom.xml, sonar-php-plugin/pom.xml
Use `${revision}` property to configure the version of the maven project. This way artifact version can be set via command-line and doesn't require modification of the files before the build. This will avoid the SQ warning about "Missing blame information... "
Also bumping the version it's easier because only the main pom of the project needs to be updated.
See https://maven.apache.org/maven-ci-friendly.html
=> Use ${revision} and flatten maven plugin to set artifact version

its/ruling/src/test/resources/expected/php-S1603.json, php-checks/src/main/java/org/sonar/php/checks/ConstructorDeclarationCheck.java, php-checks/src/test/java/org/sonar/php/checks/ConstructorDeclarationCheckTest.java, php-checks/src/test/resources/checks/ConstructorDeclarationInNamespaceCheck.php
If a class is in a namespace, a method is no longer used as a constructor if it has the same name as the class. If there is a namespace that is declared at the file script level, then all classes belong to this namespace. If there are several namespaces, classes can belong to different namespaces,
but each class must then belong to one namespace.
=> SONARPHP-884 Identify if class declaration is in namespace

php-checks/src/main/java/org/sonar/php/checks/OverwrittenArrayElementCheck.java, php-checks/src/test/resources/checks/OverwrittenArrayElementCheck.php
Fix false positives related to global array writes and having a flow-breaking statement (e.g., "continue;") between two separate writes.
=> SONARPHP-764 fix false positives

php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4784.html, php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4784.json, php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4787.html, sonarpedia.json
Metadata of all rules was updated (no need to redo if we are going to release these days).
=> SONARPHP-1075: S4784 should be deprecated because it's too noisy

php-checks/src/test/resources/checks/EmptyDatabasePasswordCheck.php, php-frontend/src/main/java/org/sonar/php/tree/visitors/AssignmentExpressionVisitor.java, php-frontend/src/test/java/org/sonar/php/tree/visitors/AssignmentExpressionVisitorTest.java
The PR adds basic handling of the `list(....) = ....` construct in `AssignmentExpressionVisitor` to fix the false positive cause, but also assign the correct value in case of something simple such as `list($a, $b) = ['a value', 'b value']`. 
More complex usages of `list()` such as when it is nested in another `list()`, or the values are assigned based on keys, are not handled in this PR.
=> SONARPHP-1117 FP on S2115 where a variable is reassigned using "list"

php-checks/src/main/java/org/sonar/php/checks/EmptyMethodCheck.java
I'm not sure whether something should be done about tests.
Adding a test with an Arabic locale for this specific class would be weird.
Maybe we could add an integration test running all rules (ruling?).
We may consider that if we hit a similar bug in the future.
=> SONARPHP-1171 Fix crash in EmptyMethodCheck with Arabic locale

php-frontend/src/main/java/org/sonar/php/api/PHPKeyword.java, php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java, php-frontend/src/main/java/org/sonar/php/parser/PHPLexicalGrammar.java, php-frontend/src/main/java/org/sonar/php/parser/TreeFactory.java, php-frontend/src/main/java/org/sonar/php/tree/impl/declaration/EnumDeclarationTreeImpl.java, php-frontend/src/main/java/org/sonar/php/tree/impl/statement/EnumCaseTreeImpl.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/Tree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/EnumDeclarationTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/statement/EnumCaseTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/visitors/PHPVisitorCheck.java, php-frontend/src/main/java/org/sonar/plugins/php/api/visitors/VisitorCheck.java, php-frontend/src/test/java/org/sonar/php/parser/KeywordTest.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/EnumDeclarationTest.java, php-frontend/src/test/java/org/sonar/php/parser/statement/EnumCaseTest.java, php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/EnumDeclarationTreeTest.java, php-frontend/src/test/java/org/sonar/php/tree/impl/statement/EnumCaseTreeTest.java, php-frontend/src/test/java/org/sonar/php/tree/visitors/PHPVisitorCheckTest.java, php-frontend/src/test/resources/visitors/test.php
Goal of this PR is parsing of a first really simple enum. 
`EnumDeclarationTree` is subject to change in the next Ticket (SONARPHP-1259) in which it might extend `ClassDeclarationTree`. I wanted to avoid doing that in this PR to keep it simple and incremental.
=> SONARPHP-1257 Parser should support basic enums

php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java, php-frontend/src/main/java/org/sonar/php/parser/PHPLexicalGrammar.java, php-frontend/src/main/java/org/sonar/php/parser/TreeFactory.java, php-frontend/src/main/java/org/sonar/php/tree/impl/declaration/ClassDeclarationTreeImpl.java, php-frontend/src/main/java/org/sonar/php/tree/impl/declaration/EnumDeclarationTreeImpl.java, php-frontend/src/main/java/org/sonar/php/tree/impl/statement/EnumCaseTreeImpl.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/ClassDeclarationTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/ClassMemberTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/EnumDeclarationTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/statement/EnumCaseTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/visitors/PHPVisitorCheck.java, php-frontend/src/main/java/org/sonar/plugins/php/api/visitors/VisitorCheck.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/EnumDeclarationTest.java, php-frontend/src/test/java/org/sonar/php/parser/statement/EnumCaseTest.java, php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/EnumDeclarationTreeTest.java, php-frontend/src/test/java/org/sonar/php/tree/impl/statement/EnumCaseTreeTest.java, php-frontend/src/test/java/org/sonar/php/tree/visitors/PHPVisitorCheckTest.java
Note that I purposefully did remove the `visitEnumDeclaration()` method, even though an enum declaration has its tree `EnumDeclarationTree`. To visit an enum declaration, one would need to use `visitClassDeclaration()`. Reasons:
- We do not have a `visitTraitDeclaration()` or `visitInterfaceDeclaration()` neither. We do use `visitClassDeclaration()` and differentiate by kind **if** necessary.
- Relying on `visitClassDeclaration()` has the advantage that we do not have to go in all the places where `visitClassDeclaration()` is used and think about if we require applying the same logic for enums. Example: scope tracking in symbol table building.
I admit that using `visitClassDeclaration()` for all of this can be confusing. Ideally, we would have something like a `ClassLikeTree` and …
=> SONARPHP-1259 Parser should support enums class-like syntax

php-frontend/src/main/java/org/sonar/php/api/PHPKeyword.java, php-frontend/src/main/java/org/sonar/php/parser/PHPLexicalGrammar.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/ClassDeclarationTest.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/FunctionDeclarationTest.java
During implementation I discovered a small potential mistake in old code. I did create SONARPHP-1267 to capture this, and did add some comments and tests. I'm not 100% yet if there was actually a reason to do it that way, so I'd rather keep this for a future hardening sprint as it has been like this for a long time, has minimal FN impact, and is not related to PHP 8.1.
What was done for `readonly` is similar to what PHP did here https://github.com/php/php-src/commit/76348f3378dbc0c92568380d23a8d75a777ae49c
=> SONARPHP-1266 Parser should allow "readonly" as function name

its/plugin/projects/common-rules/reports/phpunit.coverage.xml, its/plugin/projects/phpunit/reports/phpunit.coverage.unknown.xml, its/plugin/projects/phpunit/reports/phpunit.coverage.windows.xml, its/plugin/projects/phpunit/reports/phpunit.coverage.xml, its/plugin/projects/phpunit/reports/phpunit.tests.unknown.xml, its/plugin/projects/phpunit/reports/phpunit.tests.xml, its/plugin/tests/src/test/java/com/sonar/it/php/CommonRulesTest.java, its/plugin/tests/src/test/java/com/sonar/it/php/PHPUnitLegacyTest.java, its/plugin/tests/src/test/java/com/sonar/it/php/PHPUnitTest.java, its/plugin/tests/src/test/java/com/sonar/it/php/ReportWithUnresolvedPathTest.java, sonar-php-plugin/src/main/java/org/sonar/plugins/php/ExternalReportFileHandler.java, sonar-php-plugin/src/main/java/org/sonar/plugins/php/phpunit/CoverageResultImporter.java, sonar-php-plugin/src/main/java/org/sonar/plugins/php/phpunit/PhpUnitReportImporter.java, sonar-php-plugin/src/main/java/org/sonar/plugins/php/phpunit/TestFileReport.java, sonar-php-plugin/src/main/java/org/sonar/plugins/php/phpunit/TestResultImporter.java, sonar-php-plugin/src/test/java/org/sonar/plugins/php/ExternalReportFileHandlerTest.java, sonar-php-plugin/src/test/java/org/sonar/plugins/php/phpunit/CoverageResultImporterTest.java, sonar-php-plugin/src/test/java/org/sonar/plugins/php/phpunit/TestFileReportTest.java, sonar-php-plugin/src/test/resources/FileHandler/index.php, sonar-php-plugin/src/test/resources/FileHandler/subfolder/index.php, sonar-php-plugin/src/test/resources/org/sonar/plugins/php/phpunit/sensor/phpunit.coverage-fqn.xml, sonar-php-plugin/src/test/resources/org/sonar/plugins/php/phpunit/sensor/phpunit.coverage-fqn_win.xml
This PR changes many test resources, as they had to be adapted for the new logic. In the past, a hacky solution adjusted all paths before analyzing to an absolute path matching the test environment. The new implementation makes this hack unnecessary. The focus of this PR is on the new ExternalReportFileHandler, which makes the changes to the file paths as described in the ticket.
The missing coverage is not trivial to solve, because the tests for the coverage creation are done on a UNIX system. However, the test are properly executed in the Windows build step of the CI pipeline
=> SONARPHP-1320 Implement file path adjustment for PHPUnit test and coverage reports

.cirrus.yml
We don't need to cache Sonar for the build task
=> SONARPHP-1485 Get rid of plugin txt file for cache fingerprinting

its/plugin/tests/src/test/java/com/sonar/it/php/Tests.java
The recent change in sonar scanner: https://github.com/SonarSource/sonarqube/blob/ef0a7e8dec055928331527b5d9598387873ab085/sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/ScannerPluginRepository.java#L73 introduced a new warning in logs when `sonar.plugins.downloadOnlyRequired` is set to `false`. This setting is needed for our integration tests. 
This PR fix qa build on master: https://cirrus-ci.com/task/6184200378777600
=> Fix QA build on master due to changes in sonar scanner

.cirrus.yml, README.md, build-logic/src/main/kotlin/org.sonarsource.php.rule-api.gradle.kts, build.gradle.kts
[SONARPHP-1522](https://sonarsource.atlassian.net/browse/SONARPHP-1522)
[SONARPHP-1522]: https://sonarsource.atlassian.net/browse/SONARPHP-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1522 Migrate ruleApi to Gradle

php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java, php-frontend/src/main/java/org/sonar/php/parser/PHPLexicalGrammar.java, php-frontend/src/main/java/org/sonar/php/parser/TreeFactory.java, php-frontend/src/main/java/org/sonar/php/tree/impl/declaration/DnfIntersectionTypeTreeImpl.java, php-frontend/src/main/java/org/sonar/php/tree/impl/declaration/DnfTypeTreeImpl.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/Tree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/DnfIntersectionTypeTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/DnfTypeTree.java, php-frontend/src/main/java/org/sonar/plugins/php/api/visitors/PHPVisitorCheck.java, php-frontend/src/main/java/org/sonar/plugins/php/api/visitors/VisitorCheck.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/DnfInterfactionTypeTest.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/DnfTypeTest.java, php-frontend/src/test/java/org/sonar/php/parser/declaration/FunctionDeclarationTest.java, php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/DnfTypeTreeTest.java, php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/FunctionDeclarationTreeTest.java, php-frontend/src/test/java/org/sonar/php/tree/visitors/PHPSubscriptionCheckTest.java, php-frontend/src/test/java/org/sonar/php/tree/visitors/PHPVisitorCheckTest.java, php-frontend/src/test/resources/visitors/test.php
[SONARPHP-1533](https://sonarsource.atlassian.net/browse/SONARPHP-1533)
[SONARPHP-1533]: https://sonarsource.atlassian.net/browse/SONARPHP-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1533 Support Disjunctive Normal Form Types (PHP 8.2 feature)

its/plugin/projects/php8-features/src/propertyHooks.php, its/plugin/tests/src/integrationTest/java/com/sonar/it/php/Tests.java, php-frontend/src/main/java/org/sonar/php/tree/symbols/SymbolVisitor.java, php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolTableImplTest.java
[SONARPHP-1570](https://sonarsource.atlassian.net/browse/SONARPHP-1570)
[SONARPHP-1570]: https://sonarsource.atlassian.net/browse/SONARPHP-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1570 Symbols should be created for tree inside PropertyHooks

.github/workflows/bump-versions.yaml, php-custom-rules-plugin/README.md, php-custom-rules-plugin/build.gradle.kts, php-custom-rules-plugin/maven/pom.xml, php-frontend/build.gradle.kts
[SONARPHP-1567](https://sonarsource.atlassian.net/browse/SONARPHP-1567)
[SONARPHP-1567]: https://sonarsource.atlassian.net/browse/SONARPHP-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1567 Add Maven build system to custom rules

.cirrus/modules/qa.star
[SONARPHP-1580](https://sonarsource.atlassian.net/browse/SONARPHP-1580)
Caused by a change in cache instruction in cirrus-modules
[SONARPHP-1580]: https://sonarsource.atlassian.net/browse/SONARPHP-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1580 Fix Cirrus cache key for Windows task

.cirrus/modules/qa.star
[SONARPHP-1586](https://sonarsource.atlassian.net/browse/SONARPHP-1586)
[SONARPHP-1586]: https://sonarsource.atlassian.net/browse/SONARPHP-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1586 Set SonarQube version back to DEV for qa tasks

php-checks/src/main/java/org/sonar/php/checks/BooleanEqualityComparisonCheck.java, php-checks/src/test/resources/checks/BooleanEqualityComparisonCheck.php
[SONARPHP-1530](https://sonarsource.atlassian.net/browse/SONARPHP-1530)
[SONARPHP-1530]: https://sonarsource.atlassian.net/browse/SONARPHP-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1530 S1125 should raise an issue when a boolean literal is used in a xor expression

php-checks/src/main/java/org/sonar/php/checks/HttpOnlyCheck.java, php-checks/src/test/resources/checks/HttpOnlyCheck.php
[SONARPHP-1582](https://sonarsource.atlassian.net/browse/SONARPHP-1582)
[SONARPHP-1582]: https://sonarsource.atlassian.net/browse/SONARPHP-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1582 S3330: Only raise for variable cookies

sonar-php-plugin/src/main/java/org/sonar/plugins/php/PhpPlugin.java
[SONARPHP-1607](https://sonarsource.atlassian.net/browse/SONARPHP-1607)
Reverts SonarSource/sonar-php#1350 in order for SonarQube for IDE to be able to adapt to these changes
[SONARPHP-1607]: https://sonarsource.atlassian.net/browse/SONARPHP-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "SONARPHP-1607 Replace call to deprecated sonar-api method"

.cirrus.star
[BUILD-7451](https://sonarsource.atlassian.net/browse/BUILD-7451)
That way it use the name of the year attributed to DevInfra Team.
[BUILD-7451]: https://sonarsource.atlassian.net/browse/BUILD-7451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-7451 Update comment

php-checks/src/main/java/org/sonar/php/checks/regex/GroupReplacementCheck.java, php-checks/src/test/resources/checks/regex/GroupReplacementCheck.php
[SONARPHP-1631](https://sonarsource.atlassian.net/browse/SONARPHP-1631)
[SONARPHP-1631]: https://sonarsource.atlassian.net/browse/SONARPHP-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1631 S6328: Do not raise on escape sequences that are using numbers

build.gradle.kts
[SONARPHP-1662](https://sonarsource.atlassian.net/browse/SONARPHP-1662)
`sonar.sca.excludedManifests` is deprecated in SQS 2025.3 and is replaced with `sonar.sca.exlusions`. The behavior is exactly the same, this is just a rename to better match other sonar properties.
[SONARPHP-1662]: https://sonarsource.atlassian.net/browse/SONARPHP-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1662 chore: Use renamed sonar.sca.exclusions property

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml, .github/workflows/ToggleLockBranch.yml, .github/workflows/bump-versions.yaml, .github/workflows/mark-stale-pull-requests.yml, .github/workflows/releasability-status.yaml, .github/workflows/rule-metadata-update.yml, .github/workflows/slack-notify.yaml
[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-8073 Migrate public repositories workflows to large runners

.github/renovate.json
[SONARPHP-1691](https://sonarsource.atlassian.net/browse/SONARPHP-1691)
Part of 
[SONARPHP-1691]: https://sonarsource.atlassian.net/browse/SONARPHP-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1691 Configure Renovate to pin digests of third-party GHAs

php-frontend/src/main/java/org/sonar/php/parser/CaseInsensitiveStringExpression.java, php-frontend/src/main/java/org/sonar/php/parser/PHPLexicalGrammar.java, php-frontend/src/test/java/org/sonar/php/parser/KeywordTest.java
[SONARPHP-1692](https://sonarsource.atlassian.net/browse/SONARPHP-1692)
Replaces the expensive use of regex to parse case-insensitive keywords with a more efficient dedicated case-insensitive expression.
External contribution by @dreis2211, thanks to him!
Original PR (with more explanations): https://github.com/SonarSource/sonar-php/pull/1427
[SONARPHP-1692]: https://sonarsource.atlassian.net/browse/SONARPHP-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1692 Optimize keyword parsing by replacing regex-based logic

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml, .github/workflows/ToggleLockBranch.yml, .github/workflows/bump-versions.yaml, .github/workflows/mark-stale-pull-requests.yml, .github/workflows/releasability-status.yaml, .github/workflows/rule-metadata-update.yml, .github/workflows/slack-notify.yaml
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
=> BUILD-8875: Migrate to standardized GitHub runner names

php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolQualifiedNameTest.java
[SONARPHP-1717](https://sonarsource.atlassian.net/browse/SONARPHP-1717)
Part of 
[SONARPHP-1717]: https://sonarsource.atlassian.net/browse/SONARPHP-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPHP-1717 Improve code coverage for SymbolQualifiedNameTest
