SonarSource/sonar-php

- its/ruling/src/test/resources/expected/php-S1192.json
- php-checks/src/main/java/org/sonar/php/checks/StringLiteralDuplicatedCheck.java
- php-checks/src/test/java/org/sonar/php/checks/StringLiteralDuplicatedCheckTest.java
- php-checks/src/test/resources/checks/StringLiteralDuplicatedCheck.php
> SONARPHP-566 False positive StringLiteralDuplicatedCheck

- php-checks/src/main/java/org/sonar/php/checks/LocalVariableShadowsClassFieldCheck.java
- php-checks/src/test/resources/checks/LocalVariableShadowsClassFieldCheck.php
> SONARPHP-616 Improve LocalVariableShadowsClassFieldCheck

- its/plugin/tests/src/test/java/com/sonar/it/php/PHPIntegrationTest.java
- its/plugin/tests/src/test/java/com/sonar/it/php/PHPUnitLegacyTest.java
- its/plugin/tests/src/test/java/com/sonar/it/php/PHPUnitTest.java
- php-frontend/src/main/java/org/sonar/php/metrics/CognitiveComplexityVisitor.java
- php-frontend/src/main/java/org/sonar/php/metrics/FileMeasures.java
- php-frontend/src/main/java/org/sonar/php/metrics/MetricsVisitor.java
- php-frontend/src/test/java/org/sonar/php/metrics/CognitiveComplexityVisitorTest.java
- php-frontend/src/test/java/org/sonar/php/metrics/MetricsVisitorTest.java
- php-frontend/src/test/resources/metrics/file_cognitive_complexity.php
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/PHPSensor.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PHPSensorTest.java
> SONARJAVA-681 Compute file cognitive complexity

- README.md
> Updated links for demo and available rules

- .cix.yml
- its/plugin/tests/pom.xml
- its/plugin/tests/src/test/java/com/sonar/it/php/NonPhpProjectTest.java
- its/plugin/tests/src/test/java/com/sonar/it/php/Tests.java
- its/ruling/src/test/java/org/sonar/php/it/PHPRulingTest.java
- pom.xml
* Upgrade to Orchestrator 3.19
> Fix support of SonarQube 7.2 in integration tests

- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S2737.html
- php-checks/src/test/resources/checks/CatchRethrowingCheck.php
> illegal usage of object operator

- php-frontend/src/main/java/org/sonar/php/cfg/ControlFlowGraphBuilder.java
- php-frontend/src/test/java/org/sonar/php/cfg/CfgPrinter.java
- php-frontend/src/test/java/org/sonar/php/cfg/ControlFlowGraphTest.java
> SONARPHP-836 CFG: visit ELSE, ELSEIF statements

- .travis.yml
This reverts commit 54fe8a31c2477637373c4a1abdea0704e1891b78.
> Revert "Use JDK8 for a build (tmp)"

- its/plugin/tests/pom.xml
- its/plugin/tests/src/test/java/com/sonar/it/php/SonarLintTest.java
- pom.xml
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PHPProfileDefinitionTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PHPRulesDefinitionTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PHPSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PhpIniSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PhpPluginTest.java
NoSonar test was removed because the API has changed and it is not possible to test it this way anymore. I think that test in ITs is sufficient.
> SONARPHP-955 Update to 7.9 API

- php-checks/src/main/java/org/sonar/php/checks/EmptyDatabasePasswordCheck.java
- php-checks/src/main/java/org/sonar/php/checks/EncryptionModeAndPaddingCheck.java
- php-checks/src/main/java/org/sonar/php/checks/HashFunctionCheck.java
- php-checks/src/main/java/org/sonar/php/checks/NoPaddingRsaCheck.java
- php-checks/src/main/java/org/sonar/php/checks/SSLCertificatesVerificationDisabledCheck.java
- php-checks/src/main/java/org/sonar/php/checks/SSLHostVerificationDisabledCheck.java
- php-checks/src/main/java/org/sonar/php/checks/SessionCookiePersistenceCheck.java
- php-checks/src/main/java/org/sonar/php/checks/WeakSSLProtocolCheck.java
- php-checks/src/main/java/org/sonar/php/checks/security/LDAPAuthenticatedConnectionCheck.java
- php-checks/src/main/java/org/sonar/php/checks/security/RobustCipherAlgorithmCheck.java
- php-checks/src/main/java/org/sonar/php/checks/utils/FunctionArgumentCheck.java
- php-checks/src/test/resources/checks/EmptyDatabasePasswordCheck.php
- php-checks/src/test/resources/checks/EncryptionModeAndPaddingCheck.php
- php-checks/src/test/resources/checks/HashFunctionCheck.php
- php-checks/src/test/resources/checks/NoPaddingRsaCheck.php
- php-checks/src/test/resources/checks/SSLCertificatesVerificationDisabledCheck.php
- php-checks/src/test/resources/checks/SSLHostVerificationDisabledCheck.php
- php-checks/src/test/resources/checks/SessionCookiePersistence.php
- php-checks/src/test/resources/checks/WeakSSLProtocolCheck.php
- php-checks/src/test/resources/checks/security/LDAPAuthenticatedConnectionCheck.php
- php-checks/src/test/resources/checks/security/RobustCipherAlgorithmCheck.php
We may have a conflict when trying to merge because of 3d291e1.
> SONARPHP-1057 Adapt existing vulnerabilities to named arguments

- php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java
- php-frontend/src/main/java/org/sonar/php/tree/symbols/SymbolVisitor.java
- php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolTableImplTest.java
- php-frontend/src/test/resources/symbols/namespace_declared_types.php
Contains the same changes we had in our temporary testing branch. I've just cleaned the commits and created a ticket for it.
> SONARPHP-1082: Add fully-qualified class names to declared types.

- pom.xml
- sonar-php-plugin/pom.xml
To get rid of illegal reflective access.
> SONARPHP-1072 Update SSLR to 1.24

- php-frontend/src/test/java/org/sonar/php/metrics/ExecutableLineVisitorTest.java
Duplicates #784 to trigger full QA.
> Fix a flaky test

- sonar-php-plugin/src/main/java/org/sonar/plugins/php/PhpPlugin.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PhpPluginTest.java
https://jira.sonarsource.com/browse/SONARPHP-1172
> SONARPHP-1172 Remove usage of deprecated `Qualifiers.MODULE`

- php-checks/src/main/java/org/sonar/php/checks/UnusedPrivateMethodCheck.java
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S1144.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S1144.json
- php-checks/src/test/resources/checks/UnusedPrivateMethodCheck.php
Related RSPEC PR: https://github.com/SonarSource/rspec/pull/614
> SONARPHP-1264 S1144 UnusedPrivateMethodCheck should raise on enum private and protected methods

- its/ruling/src/test/resources/expected/php-S6323.json
- php-checks/src/test/resources/checks/regex/EmptyAlternativeCheck.php
- pom.xml
The real job was done on sonar-analyzer-commons (see https://github.com/SonarSource/sonar-analyzer-commons/pull/208)
Here only a few test cases were fixed.
> SONARPHP-1283:  Fix a misinterpretation of SONARPHP-1274 (rule S6323)

- php-checks/src/main/java/org/sonar/php/checks/ArgumentWithDefaultValueNotLastCheck.java
- php-checks/src/main/java/org/sonar/php/checks/UseOfEmptyReturnValueCheck.java
- php-checks/src/main/java/org/sonar/php/checks/utils/argumentmatching/ArgumentVerifierUnaryFunction.java
- php-frontend/src/main/java/org/sonar/php/tree/impl/expression/LiteralTreeImpl.java
- php-frontend/src/main/java/org/sonar/php/tree/impl/expression/NameIdentifierTreeImpl.java
- php-frontend/src/main/java/org/sonar/php/tree/symbols/Scope.java
- php-frontend/src/main/java/org/sonar/php/tree/symbols/SymbolVisitor.java
- php-frontend/src/main/java/org/sonar/plugins/php/api/cfg/ControlFlowGraph.java
- php-frontend/src/main/java/org/sonar/plugins/php/api/cfg/PhpCfgBlock.java
- php-frontend/src/main/java/org/sonar/plugins/php/api/tests/PHPCheckVerifier.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/PHPProfileDefinition.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/PhpIniSensor.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/reports/phpunit/xml/TestCase.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/reports/phpunit/xml/TestSuite.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/reports/phpunit/xml/TestSuites.java
Also:
SONARPHP-1161 Remove dependency on guava's VisibleForTesting annotation 
SONARPHP-1165 Remove dependency on guava's checkNotNull function
> SONARPHP-1157 Remove dependency on guava's Joiner class

- php-custom-rules/README.md
- php-custom-rules/pom.xml
- php-custom-rules/src/main/java/org/sonar/samples/php/MyPhpRules.java
- php-custom-rules/src/main/java/org/sonar/samples/php/PHPCustomRulesPlugin.java
- php-custom-rules/src/main/java/org/sonar/samples/php/checks/ForbiddenFunctionUseCheck.java
- php-custom-rules/src/main/java/org/sonar/samples/php/checks/OtherForbiddenFunctionUseCheck.java
- php-custom-rules/src/main/resources/org/sonar/l10n/php/rules/custom/S1.html
- php-custom-rules/src/main/resources/org/sonar/l10n/php/rules/custom/S2.html
- php-custom-rules/src/test/java/org/sonar/samples/php/MyPhpRulesTest.java
- php-custom-rules/src/test/java/org/sonar/samples/php/PHPCustomRulesPluginTest.java
- php-custom-rules/src/test/java/org/sonar/samples/php/checks/ForbiddenFunctionUseCheckTest.java
- php-custom-rules/src/test/java/org/sonar/samples/php/checks/OtherForbiddenFunctionUseCheckTest.java
- php-custom-rules/src/test/resources/checks/forbiddenFunctionUseCheck.php
- pom.xml
Better review commit by commit. The first is just a copy from another repo, and the second commit update the custom rule project.
It also works with SQ.
> SONARPHP-1302 Move custom rules example to sonar-php

- its/ruling/src/test/resources/expected/PHP_CodeSniffer/php-S4144.json
- php-checks/src/main/java/org/sonar/php/checks/DuplicatedArgumentCheck.java
- php-checks/src/main/java/org/sonar/php/checks/DuplicatedMethodCheck.java
- php-checks/src/main/java/org/sonar/php/checks/utils/CheckUtils.java
- php-checks/src/test/resources/checks/DuplicatedMethodCheck.php
Corresponding RSPEC PR: https://github.com/SonarSource/rspec/pull/2969
> SONARPHP-1460 S4144 Add exceptions for simple return statements

- README.md
- php-custom-rules/README.md
You can see the result here: https://github.com/SonarSource/sonar-php/tree/SONARPHP-1465
> SONARPHP-1465 Update project badges in repo

- php-checks/src/test/resources/checks/regex/InvalidRegexCheck.php
- pom.xml
Required change in commons: https://github.com/SonarSource/sonar-analyzer-commons/pull/317
> SONARPHP-1383 FP S5856 Regex: Expected octal digit, but found '\'

- php-checks/src/main/java/org/sonar/php/checks/security/AuthorizationsCheck.java
No change on build file, just a small formating impact.
> Update sonar-formatter to version 23.

- pom.xml
I didn't update the rule metadata as it will be done anyway during the release process.
> SONARPHP-1505 Add STIG metadata support

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
[SONARPHP-1547](https://sonarsource.atlassian.net/browse/SONARPHP-1547)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last line …
> SONARPHP-1547 Add Jira integration

- php-checks/src/main/java/org/sonar/php/checks/HardCodedSecretCheck.java
- php-checks/src/test/resources/checks/HardCodedSecretCheckAST.php
[SONARPHP-1557](https://sonarsource.atlassian.net/browse/SONARPHP-1557)
Part of 
[SONARPHP-1557]: https://sonarsource.atlassian.net/browse/SONARPHP-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1557 Detects hard-coded secrets in strings

- php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java
- php-frontend/src/test/java/org/sonar/php/parser/expression/CallableConvertTest.java
- php-frontend/src/test/java/org/sonar/php/parser/expression/MemberExpressionTest.java
- php-frontend/src/test/java/org/sonar/php/parser/expression/NewExpressionTest.java
- php-frontend/src/test/java/org/sonar/php/tree/impl/expression/NewExpressionTreeTest.java
[SONARPHP-1544](https://sonarsource.atlassian.net/browse/SONARPHP-1544)
[SONARPHP-1544]: https://sonarsource.atlassian.net/browse/SONARPHP-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1544 Support new without parentheses

- php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java
- php-frontend/src/main/java/org/sonar/php/parser/TreeFactory.java
- php-frontend/src/main/java/org/sonar/php/tree/impl/declaration/ParameterTreeImpl.java
- php-frontend/src/main/java/org/sonar/plugins/php/api/tree/declaration/ParameterTree.java
- php-frontend/src/test/java/org/sonar/php/parser/declaration/FunctionDeclarationTest.java
- php-frontend/src/test/java/org/sonar/php/parser/declaration/MethodDeclarationTest.java
- php-frontend/src/test/java/org/sonar/php/parser/declaration/ParameterListTest.java
- php-frontend/src/test/java/org/sonar/php/parser/declaration/ParameterTest.java
- php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/FunctionDeclarationTreeTest.java
- php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/MethodDeclarationTreeTest.java
- php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/ParameterListTreeTest.java
- php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/ParameterTreeTest.java
[SONARPHP-1563](https://sonarsource.atlassian.net/browse/SONARPHP-1563)
Part of 
[SONARPHP-1563]: https://sonarsource.atlassian.net/browse/SONARPHP-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1563 Add support for PropertyHooks in constructor parameters

- .github/workflows/ToggleLockBranch.yml
[SONARPHP-1565](https://sonarsource.atlassian.net/browse/SONARPHP-1565)
To review - make sure that 
* there's only one file
* the file is the same as [ToggleLockBranch.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/ToggleLockBranch.yml)
* The slack channel on the last line is correct for this repo
[SONARPHP-1565]: https://sonarsource.atlassian.net/browse/SONARPHP-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1565 Add ToggleLockBranch.yml

- .cirrus/modules/build.star
[SONARPHP-1523](https://sonarsource.atlassian.net/browse/SONARPHP-1523)
[SONARPHP-1523]: https://sonarsource.atlassian.net/browse/SONARPHP-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1523 Fix WhiteSource task in CI

- php-frontend/src/main/java/org/sonar/php/tree/symbols/SymbolVisitor.java
- php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolTableImplTest.java
[SONARPHP-1570](https://sonarsource.atlassian.net/browse/SONARPHP-1570)
[SONARPHP-1570]: https://sonarsource.atlassian.net/browse/SONARPHP-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1570 Symbols should be created for tree inside PropertyHooks in constructor functions

- gradle/libs.versions.toml
[SONARPHP-1574](https://sonarsource.atlassian.net/browse/SONARPHP-1574)
Part of 
[SONARPHP-1574]: https://sonarsource.atlassian.net/browse/SONARPHP-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1574 Upgrade sonar-analyzer-commons to 2.16.0.3141

- .cirrus/modules/qa.star
[SONARPHP-1576](https://sonarsource.atlassian.net/browse/SONARPHP-1576)
Part of 
[SONARPHP-1576]: https://sonarsource.atlassian.net/browse/SONARPHP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1576 Fix orchestrator version to 10.8

- its/ruling/src/integrationTest/resources/expected/PHP_CodeSniffer/php-S1068.json
- php-checks/src/main/java/org/sonar/php/checks/UnusedPrivateFieldCheck.java
- php-checks/src/test/java/org/sonar/php/checks/UnusedPrivateFieldCheckTest.java
- php-checks/src/test/resources/checks/UnusedPrivateFieldCheck.php
- php-frontend/src/main/java/org/sonar/php/tree/symbols/SymbolVisitor.java
- php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolTableImplTest.java
- php-frontend/src/test/resources/symbols/symbolTable.php
This reverts commit bcaf88df05cd4f0339c1f644c320cafddfc0dd43.
Part of SONARPHP-1583
> Revert "SONARPHP-1583 Constructor promoted properties should generate class member symbol (#1330)"

- php-frontend/src/main/java/org/sonar/php/parser/LexicalConstant.java
- php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java
- php-frontend/src/main/java/org/sonar/php/parser/PHPLexicalGrammar.java
- php-frontend/src/test/java/org/sonar/php/parser/PHPParserTest.java
- php-frontend/src/test/java/org/sonar/php/parser/declaration/ClassMemberTest.java
- php-frontend/src/test/java/org/sonar/php/parser/declaration/MethodDeclarationTest.java
- php-frontend/src/test/java/org/sonar/php/tree/impl/declaration/ClassPropertyDeclarationTreeTest.java
- php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolTableImplTest.java
- php-frontend/src/test/resources/symbols/symbolTable.php
[SONARPHP-1584](https://sonarsource.atlassian.net/browse/SONARPHP-1584)
[SONARPHP-1584]: https://sonarsource.atlassian.net/browse/SONARPHP-1584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1584 Support Asymmetric Property Visibility

- its/README.md
[SONARPHP-1572](https://sonarsource.atlassian.net/browse/SONARPHP-1572)
[SONARPHP-1572]: https://sonarsource.atlassian.net/browse/SONARPHP-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1572 Update readme of integration tests

- its/ruling/src/integrationTest/resources/expected/PHP_CodeSniffer/php-S1068.json
- php-checks/src/main/java/org/sonar/php/checks/UnusedPrivateFieldCheck.java
- php-checks/src/test/java/org/sonar/php/checks/UnusedPrivateFieldCheckTest.java
- php-checks/src/test/resources/checks/UnusedPrivateFieldCheck.php
- php-frontend/src/main/java/org/sonar/php/tree/symbols/SymbolVisitor.java
- php-frontend/src/test/java/org/sonar/php/tree/symbols/SymbolTableImplTest.java
- php-frontend/src/test/resources/symbols/symbolTable.php
[SONARPHP-1583](https://sonarsource.atlassian.net/browse/SONARPHP-1583)
[SONARPHP-1583]: https://sonarsource.atlassian.net/browse/SONARPHP-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1583 Constructor promoted properties should generate class member symbol

- .github/workflows/rule-metadata-update.yml
[SONARPHP-1598](https://sonarsource.atlassian.net/browse/SONARPHP-1598)
Part of 
[SONARPHP-1598]: https://sonarsource.atlassian.net/browse/SONARPHP-1598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1598 Add rule-api update workflow

- build-logic/src/main/kotlin/org.sonarsource.php.integration-test.gradle.kts
- its/plugin/src/integrationTest/java/com/sonar/it/php/PHPIntegrationTest.java
- sonarpedia.json
[SONARPHP-1595](https://sonarsource.atlassian.net/browse/SONARPHP-1595)
Part of 
[SONARPHP-1595]: https://sonarsource.atlassian.net/browse/SONARPHP-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1595 DEV plugin ITS should not use cache when underlying SQS version is changing

- its/plugin/src/integrationTest/java/com/sonar/it/php/PHPIntegrationTest.java
- php-frontend/src/test/java/org/sonar/php/metrics/MetricsVisitorTest.java
[SONARPHP-1596](https://sonarsource.atlassian.net/browse/SONARPHP-1596)
Part of 
[SONARPHP-1596]: https://sonarsource.atlassian.net/browse/SONARPHP-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1596 Adjust ITS for removal of ncloc_data metric

- its/ruling/src/integrationTest/resources/expected/PHPWord/php-S1192.json
- php-checks/src/main/java/org/sonar/php/checks/StringLiteralDuplicatedCheck.java
- php-checks/src/main/java/org/sonar/php/checks/utils/RegexUtils.java
- php-checks/src/test/java/org/sonar/php/checks/utils/RegexUtilsTest.java
- php-checks/src/test/resources/checks/StringLiteralDuplicatedCheck/default.php
- php-checks/src/test/resources/checks/UseOfUninitializedVariableCheck.php
[SONARPHP-1590](https://sonarsource.atlassian.net/browse/SONARPHP-1590)
Part of 
[SONARPHP-1590]: https://sonarsource.atlassian.net/browse/SONARPHP-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1590 S1192 should not raise for HTML tags

- sonar-php-plugin/src/main/java/org/sonar/plugins/php/PhpPlugin.java
[SONARPHP-1607](https://sonarsource.atlassian.net/browse/SONARPHP-1607)
Part of 
[SONARPHP-1607]: https://sonarsource.atlassian.net/browse/SONARPHP-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1607 Replace call to deprecated sonar-api method

- php-frontend/src/main/java/org/sonar/php/parser/PHPGrammar.java
- php-frontend/src/test/java/org/sonar/php/parser/expression/PowerExpressionTest.java
- php-frontend/src/test/java/org/sonar/php/parser/expression/UnaryExprTest.java
[SONARPHP-1600](https://sonarsource.atlassian.net/browse/SONARPHP-1600)
[SONARPHP-1600]: https://sonarsource.atlassian.net/browse/SONARPHP-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1600 Parser should support match statements in unary expressions

- its/ruling/src/integrationTest/resources/expected/PHP_CodeSniffer/php-S4144.json
- php-checks/src/main/java/org/sonar/php/checks/DuplicatedMethodCheck.java
- php-checks/src/test/resources/checks/DuplicatedMethodCheck.php
[SONARPHP-1577](https://sonarsource.atlassian.net/browse/SONARPHP-1577)
[SONARPHP-1577]: https://sonarsource.atlassian.net/browse/SONARPHP-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1577 S4144 should not report an issue on method/function using the __FUNCTION__ constant

- its/ruling/src/integrationTest/resources/expected/PHPWord/php-S1192.json
- php-checks/src/main/java/org/sonar/php/checks/StringLiteralDuplicatedCheck.java
- php-checks/src/main/java/org/sonar/php/checks/utils/RegexUtils.java
- php-checks/src/test/java/org/sonar/php/checks/utils/RegexUtilsTest.java
- php-checks/src/test/resources/checks/StringLiteralDuplicatedCheck/default.php
- php-checks/src/test/resources/checks/UseOfUninitializedVariableCheck.php
[SONARPHP-1590](https://sonarsource.atlassian.net/browse/SONARPHP-1590)
[SONARPHP-1590]: https://sonarsource.atlassian.net/browse/SONARPHP-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1590 - S1192 should not raise for HTML tags - reapply

- .github/workflows/ToggleLockBranch.yml
- .github/workflows/release.yml
- .github/workflows/slack-notify.yaml
[SONARPHP-1622](https://sonarsource.atlassian.net/browse/SONARPHP-1622)
Part of 
[SONARPHP-1622]: https://sonarsource.atlassian.net/browse/SONARPHP-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1622 Update Slack notification channel for CI builds

- .github/renovate.json
[SONARPHP-1625](https://sonarsource.atlassian.net/browse/SONARPHP-1625)
Part of 
[SONARPHP-1625]: https://sonarsource.atlassian.net/browse/SONARPHP-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1625 Configure renovate to rebase only when conflicted

- gradle/libs.versions.toml
[SONARPHP-1627](https://sonarsource.atlassian.net/browse/SONARPHP-1627)
Part of 
[SONARPHP-1627]: https://sonarsource.atlassian.net/browse/SONARPHP-1627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1627 Add information about plugin-api update requirements

- .github/renovate.json
[SONARPHP-1628](https://sonarsource.atlassian.net/browse/SONARPHP-1628)
Part of 
[SONARPHP-1628]: https://sonarsource.atlassian.net/browse/SONARPHP-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1628 Automatic updates for plugin-api should be separate from other dependencies

- its/plugin/src/integrationTest/java/com/sonar/it/php/PHPIntegrationTest.java
- its/ruling/src/integrationTest/java/org/sonar/php/it/PhpGeneralRulingTest.java
- its/ruling/src/integrationTest/resources/expected/PHPMailer/php-S1541.json
- its/ruling/src/integrationTest/resources/expected/PHPWord/php-S1541.json
- its/ruling/src/integrationTest/resources/expected/PhpSpreadsheet/php-S1311.json
- its/ruling/src/integrationTest/resources/expected/PhpSpreadsheet/php-S1541.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S1106.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S1311.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S1578.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S2003.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S2007.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S2043.json
- its/ruling/src/integrationTest/resources/expected/monica/php-S4833.json
- its/ruling/src/integrationTest/resources/expected/psysh/php-S1541.json
- php-checks/src/main/java/org/sonar/php/checks/FunctionComplexityCheck.java
- php-checks/src/test/java/org/sonar/php/checks/FunctionComplexityCheckTest.java
- php-checks/src/test/resources/checks/FunctionComplexityCheck.php
- php-frontend/src/main/java/org/sonar/php/metrics/ComplexityVisitor.java
- php-frontend/src/test/java/org/sonar/php/metrics/ComplexityVisitorTest.java
[SONARPHP-1626](https://sonarsource.atlassian.net/browse/SONARPHP-1626)
[SONARPHP-1626]: https://sonarsource.atlassian.net/browse/SONARPHP-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1626 S1541 should detect `elseif` clauses

- gradle.properties
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S1135.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S2115.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S2245.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S2245.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S2755.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4423.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4426.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4426.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4790.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4790.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4830.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S4830.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S5332.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S5332.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S5527.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S5527.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S5542.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S5547.json
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S6418.html
- php-checks/src/main/resources/org/sonar/l10n/php/rules/php/S6437.json
- sonarpedia.json
[SONARPHP-1633](https://sonarsource.atlassian.net/browse/SONARPHP-1633)
Part of 
[SONARPHP-1633]: https://sonarsource.atlassian.net/browse/SONARPHP-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1633 Fix discrepancies between MQR and severity for PHP rules

- .cirrus/modules/build.star
- build-logic/src/main/kotlin/org/sonarsource/php/BuildUtils.kt
[SONARPHP-1634](https://sonarsource.atlassian.net/browse/SONARPHP-1634)
Part of 
[SONARPHP-1634]: https://sonarsource.atlassian.net/browse/SONARPHP-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1634 Change singing condition for release branches

- its/ruling/src/integrationTest/java/org/sonar/php/it/RulingHelper.java
[SONARPHP-1639](https://sonarsource.atlassian.net/browse/SONARPHP-1639)
Part of 
[SONARPHP-1639]: https://sonarsource.atlassian.net/browse/SONARPHP-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1639 Fix debugging in orchestrator

- .github/workflows/PullRequestClosed.yml
[SONARPHP-1640](https://sonarsource.atlassian.net/browse/SONARPHP-1640)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SONARPHP-1640]: https://sonarsource.atlassian.net/browse/SONARPHP-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1640 Autoclose issues created by Jira integration

- .github/workflows/rule-metadata-update.yml
[SONARPHP-1641](https://sonarsource.atlassian.net/browse/SONARPHP-1641)
Part of 
[SONARPHP-1641]: https://sonarsource.atlassian.net/browse/SONARPHP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1641 Fix Rule metadata update GitHub Action

- its/ruling/src/integrationTest/java/org/sonar/php/it/RulingHelper.java
- php-checks/src/main/java/org/sonar/php/checks/HardCodedCredentialsInFunctionCallsCheck.java
- php-checks/src/test/java/org/sonar/php/checks/HardCodedCredentialsInFunctionCallsCheckTest.java
- php-frontend/src/main/java/org/sonar/php/PHPAnalyzer.java
- php-frontend/src/test/java/org/sonar/php/PHPAnalyzerTest.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/AnalysisScanner.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/PhpIniSensor.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/reports/AbstractReportImporter.java
- sonar-php-plugin/src/main/java/org/sonar/plugins/php/reports/ExternalReportWildcardProvider.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PHPSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/PhpIniSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/reports/ExternalReportWildcardProviderTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/reports/ReportSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/reports/phpstan/PhpStanSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/reports/phpunit/CoverageResultImporterTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/reports/phpunit/PhpUnitSensorTest.java
- sonar-php-plugin/src/test/java/org/sonar/plugins/php/reports/phpunit/TestResultImporterTest.java
[SONARPHP-1643](https://sonarsource.atlassian.net/browse/SONARPHP-1643)
Part of 
[SONARPHP-1643]: https://sonarsource.atlassian.net/browse/SONARPHP-1643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1643 Error level log should be used only for non-recoverable error that stop the analyzer

- build.gradle.kts
[SONARPHP-1647](https://sonarsource.atlassian.net/browse/SONARPHP-1647)
Part of 
[SONARPHP-1647]: https://sonarsource.atlassian.net/browse/SONARPHP-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1647 Exclude IT sources from SCA analysis

- .cirrus/modules/build.star
- .cirrus/modules/qa.star
[SONARPHP-1648](https://sonarsource.atlassian.net/browse/SONARPHP-1648)
Part of 
[SONARPHP-1648]: https://sonarsource.atlassian.net/browse/SONARPHP-1648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1648 Increase memory for CI failing tasks

- .github/workflows/slack-notify.yaml
[SONARPHP-1652](https://sonarsource.atlassian.net/browse/SONARPHP-1652)
This PR updates the Slack notification action in .github/workflows/slack-notify.yaml.
[SONARPHP-1652]: https://sonarsource.atlassian.net/browse/SONARPHP-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUILD-7788 Migrate slack notification

- doc/CFG.md
[SONARPHP-1659](https://sonarsource.atlassian.net/browse/SONARPHP-1659)
[SONARPHP-1659]: https://sonarsource.atlassian.net/browse/SONARPHP-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1659 Update links path script CFG

- sonar-php-plugin/build.gradle.kts
[SONARPHP-1666](https://sonarsource.atlassian.net/browse/SONARPHP-1666)
Part of 
[SONARPHP-1666]: https://sonarsource.atlassian.net/browse/SONARPHP-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1666 Add missing information in generated pom

- .github/workflows/automate_release.yml
[SONARPHP-1677](https://sonarsource.atlassian.net/browse/SONARPHP-1677)
Part of 
[SONARPHP-1677]: https://sonarsource.atlassian.net/browse/SONARPHP-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1677 add automate release workflow

- .github/workflows/automate_release.yml
[SONARPHP-1683](https://sonarsource.atlassian.net/browse/SONARPHP-1683)
Part of 
[SONARPHP-1683]: https://sonarsource.atlassian.net/browse/SONARPHP-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1683 temp fix for automate release workflow

- README.md
[SONARPHP-1685](https://sonarsource.atlassian.net/browse/SONARPHP-1685)
Part of 
[SONARPHP-1685]: https://sonarsource.atlassian.net/browse/SONARPHP-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1685 update clean code links

- .github/workflows/release.yml
- .github/workflows/sonar-release.yml
[SONARPHP-1686](https://sonarsource.atlassian.net/browse/SONARPHP-1686)
Part of 
[SONARPHP-1686]: https://sonarsource.atlassian.net/browse/SONARPHP-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1686 Add Sonar Release workflow

- .github/workflows/bump-versions.yaml
[SONARPHP-1704](https://sonarsource.atlassian.net/browse/SONARPHP-1704)
Part of 
[SONARPHP-1704]: https://sonarsource.atlassian.net/browse/SONARPHP-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1704 Fix security issue on github workflow

- .github/workflows/iris.yml
- .github/workflows/shadow_scan.yml
- build.gradle.kts
- php-checks/src/main/java/org/sonar/php/checks/utils/argumentmatching/package-info.java
- php-custom-rules-plugin/src/main/java/org/sonar/samples/php/checks/package-info.java
- php-custom-rules-plugin/src/main/java/org/sonar/samples/php/package-info.java
- php-frontend/src/main/java/org/sonar/package-info.java
- php-frontend/src/main/java/org/sonar/php/filters/package-info.java
[SONARPHP-1699](https://sonarsource.atlassian.net/browse/SONARPHP-1699)
Part of 
[SONARPHP-1699]: https://sonarsource.atlassian.net/browse/SONARPHP-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1699 Implement Unified dogfooding for sonar-php

- .github/workflows/build.yml
[SONARPHP-1703](https://sonarsource.atlassian.net/browse/SONARPHP-1703)
Part of 
[SONARPHP-1703]: https://sonarsource.atlassian.net/browse/SONARPHP-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1703 Fix Slack notifications in CI

- .github/workflows/AutomateRelease.yml
[SONARPHP-1711](https://sonarsource.atlassian.net/browse/SONARPHP-1711)
Part of 
[SONARPHP-1711]: https://sonarsource.atlassian.net/browse/SONARPHP-1711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1711 Fix bump_versions action in release automation

- .github/workflows/rule-metadata-update.yml
[SONARPHP-1712](https://sonarsource.atlassian.net/browse/SONARPHP-1712)
Part of 
[SONARPHP-1712]: https://sonarsource.atlassian.net/browse/SONARPHP-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1712 Update rule-metadata-update to be consistent with other languages

- .github/workflows/pr-cleanup.yml
[SONARPHP-1718](https://sonarsource.atlassian.net/browse/SONARPHP-1718)
Part of 
[SONARPHP-1718]: https://sonarsource.atlassian.net/browse/SONARPHP-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPHP-1718 Replace deprecated github runner
